sudo: required
language: android
jdk: oraclejdk8
android:
 components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-26
    - extra-android-m2repository
before_script:
 - chmod +x gradlew
script:
- ./gradlew build --stacktrace